config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


scope module: 'member' do
	resources :addresses, only:[:index, :create, :edit, :update, :destroy]


	resources :items, only:[:index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
	resources :cart_items, only:[:create, :update, :index, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/thanks' => 'orders#thanks'
  resources :orders, only:[:new, :index, :show, :create]
	resources :members, only: [:show, :edit, :update]
  root :to => 'members#top'
  get 'confirm' => 'members#confirm'
  delete '/members/:id' => 'members#hide',as: :hide
end


namespace :admin do
	resources :genres,only: [:index,:create,:edit,:update]
	resources :items,only: [:index,:new,:create,:show,:edit,:update]
  resources :admin, only:[:index,:show,:edit,:update]
  resources :orders,only:[:index,:show,:update]
  resources :order_items,only:[:update]  
  get 'top' => 'admin#top'
end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def exist_items?(item)
  	cart_items.exists?(item_id: item.id)
  end


def full_name
    self.surname + self.name
  end

  acts_as_paranoid

validates :surname, presence: true
validates :name, presence: true
validates :kana_surname, presence: true
validates :kana_name, presence: true
validates :postal_code, presence: true, length: { is: 7 }
validates :address, presence: true
validates :phone, presence: true, length: { minimum: 8 }

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_items

	enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
	enum payment: {クレジットカード:0, 銀行振込:1}

	validates :payment, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
		before_action :authenticate_admin!
		def index
		@orders = Order.all
	    end
	    

	    def show
	    @order = Order.find(params[:id])
	    @order_items = @order.order_items
	    end

	    def update
	    @order = Order.find(params[:id])
	    @order.update(order_params)
	    redirect_to admin_orders_path
	    end

	 private
	 def order_params
	     params.require(:order).permit(:member_id, :postage, :payment, :order_status, :bill, :postal_code, :address, :address_name)
	end
end

app/controllers/member/addresses_controller.rb
class Member::AddressesController < ApplicationController
	before_action :authenticate_member!

	def index
		@address = Address.new
		@addresses = current_member.addresses
	end

	def create
		@address = Address.new(address_params)
		@address.member_id = current_member.id
		if @address.save
		   redirect_to addresses_path, notice: "successfully created Address!"
	    else
	    	@addresses = Address.all
	    	render :index
	    end
	end

	def edit
		@address = Address.find(params[:id])
	end

	def update
		@address = Address.find(params[:id])
		if @address.update(address_params)
		   redirect_to addresses_path, notice: "successfully update Address!"
		else
			render action: :edit
		end
	end

	def destroy
		@address = Address.find(params[:id])
		@address.destroy
		redirect_to addresses_path
	end

	private

  def address_params
  	params.require(:address).permit(:postal_code, :address, :address_name, :member_id)
  end

end

app/controllers/member/cart_items_controller.rb
class Member::CartItemsController < ApplicationController
	before_action :authenticate_member!

	def create
		@cart_item = CartItem.new(cart_item_params)
		@cart_item.member_id = current_member.id
		@cart_item.save
		redirect_to cart_items_path
	end

	def update
		@cart_item = CartItem.find(params[:id])
		@cart_item.update(cart_item_params)
		redirect_to cart_items_path
	end

	def index
		@cart_item = CartItem.new
		@cart_items = CartItem.where(member_id: current_member)
		@total_price = 0
		@cart_items.each do |cart_item|
			@total_price += cart_item.item.price * cart_item.number
		end
	end

	def destroy
		@cart_item = CartItem.find(params[:id])
		@cart_item.destroy
		redirect_to cart_items_path
	end

	def destroy_all
		@cart_items = CartItem.where(member_id: current_member)
		@cart_items.destroy_all
		redirect_to cart_items_path
	end

	private
	def cart_item_params
		params.require(:cart_item).permit(:item_id, :number, :member_id)
	end

end

# find:id １つのidのみ  where:id以外のカラムを複数　find_by:id以外のカラムも抜けだせる　１つだけもっていける（whereとの違い）

app/controllers/member/items_controller.rb
class Member::ItemsController < ApplicationController

	def index
		@items = Item.all.page(params[:page]).reverse_order
		@genres = Genre.all
	end

	def show
		@genres = Genre.all
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end

	private
	def item_params
		params.require(:item).permit(:genre_id, :item_name, :price, :sale_status, :item_profile, :item_image)
	end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController
	def top
		@items = Item.all
		@jenres = Genre.all
	end

	def show
	end

	def edit
		@member = current_member
	end

	def update
		@member = current_member
		if @member.update(member_params)
			redirect_to member_path(@member)
		else
			render :edit
		end
	end

	def confirm
		@member = current_member
	end

	def hide
		@member = Member.find(params[:id])
		@member.destroy
		redirect_to root_path
	end

	private
	def member_params
		params.require(:member).permit(:surname, :name, :kana_surname, :kana_name, :email, :postal_code, :address, :phone)
	end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
	before_action :authenticate_member!

	def new
		@order = Order.new
		@address = Address.new
	end

	def index
		@orders = current_member.orders
	end

	def show
		@order = Order.find(params[:id])
	end

	def create
		@order = Order.new(session[:order])
		session[:order].clear
		@order.postage = 800
		@order.order_status = 0
		current_member.cart_items.each do |cart_item|
			@order.bill = cart_item.item.price * cart_item.number
		end
		@order.save
		current_member.cart_items.each do |cart_item|
			order_item = OrderItem.new(
				order_id: @order.id,
				number: cart_item.number,
				price: cart_item.item.price,
				production_status: 0,
				item_id: cart_item.item_id
			)
			order_item.save
		end
		current_member.cart_items.destroy_all
		redirect_to orders_thanks_path
	end

	def confirm
		@order = Order.new(order_params)
		@cart_items = CartItem.where(member_id: current_member.id)
		@total_price = 0
		@cart_items.each do |cart_item|
			@total_price += cart_item.item.price * cart_item.number
		end

		add = params[:order][:add]

		if add == "ご自身の住所"
			address = params[:order][:address]
			@address = Address.find_by(id: address)
			@order.address = current_member.address
			@order.address_name = current_member.full_name
			@order.postal_code = current_member.postal_code
		elsif add == "登録済み住所からの選択"
			address = params[:order][:address]
			@address = Address.find_by(id: address)
			@order.address = @address.address
            @order.address_name = @address.address_name
            @order.postal_code = @address.postal_code
		elsif add == "新しいお届け先"
			@address = Address.new(address_params)
			@address.save
			@order.address = @address.address
            @order.address_name = @address.address_name
            @order.postal_code = @address.postal_code
		end

		session[:order] = @order
		session[:order][:bill] = @total_price+800
		session[:order][:member_id] = current_member.id
	end

	def thanks
	end

	private
	def order_params
		params.require(:order).permit(:member_id, :postage, :payment, :order_status, :bill, :postal_code, :address, :address_name)
	end

	def address_params
  		params.require(:address).permit(:postal_code, :address, :address_name, :member_id)
  	end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/address_helper.rb
module Member::AddressHelper
end

app/helpers/member/cart_items_helper.rb
module Member::CartItemsHelper
end

app/helpers/member/items_helper.rb
module Member::ItemsHelper
end

app/helpers/member/members_helper.rb
module Member::MembersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/member/orders/_newaddress.html.erb
<%= form_for(address)  do |f| %>
<table class="table table-hover table-inverse">
	<tr>
		<th colspan="4"><%= f.label :"郵便番号(ハイフンなし)" %></th>
		<td colspan="4"><%= f.text_field :postal_code, class: "postal_code" %></td>
	</tr>
	<tr>
		<th colspan="4"><%= f.label :住所 %></th>
		<td colspan="4"><%= f.text_area :address, class: "address" %></td>
	</tr>
	<tr>
		<th colspan="4"><%= f.label :宛名 %></th>
		<td colspan="4"><%= f.text_area :address_name, class: "address_name" %></td>
	</tr>
</table>
<% end %>

app/views/member/orders/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>注文情報確認</h2>

			<div class="row">
				<div class="col-xs-8">
					<table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
						<thead>
							<tr>
								<th colspan="4">商品名</th>
								<th>単価（税込）</th>
								<th>数量</th>
								<th>小計</th>
							</tr>
						</thead>
						<tbody>
							<% @cart_items.each do |cart_item| %>
							<tr>
								<td colspan="4">
									<%= attachment_image_tag cart_item.item, :item_image, size: "50x50",format: 'jpeg' %>
									<%= cart_item.item.item_name %>
								</td>
								<td><%= (cart_item.item.price * 1.1).round  %></td>
								<td><%= cart_item.number %></td>
								<td><%= cart_item.item.price * cart_item.number %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>


				<div class="col-xs-4">
					<table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
						<tbody>
							<% @sum = 0 %>
							<tr>
								<th>送料</th>
								<td>800</td>
							 </tr>
							<tr>
								<th>商品合計</th>
								<td><%= @total_price %></td>
							</tr>
							<tr>
								<% @sum = @total_price + 800 %>
								<th>請求金額</th>
								<td><%= @sum %></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

				<div class="row">
					<table class="table table-condensed">
						<tbody>
							<tr>
								<th><strong>支払方法</strong></th>
								<td><%= session[:order]["payment"] %></td>
							 </tr>
							<tr>
								<th>お届け先</th>
								<td><%= @order.postal_code %><%= @order.address %><br />
									<%= @order.address_name %></td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="row">
						<%= link_to "購入を確定する", orders_path, method: :post ,class: "btn-sm btn-success" %>
			        </div>

			        <div class="row">
					<%= link_to "注文情報入力へ戻る",new_order_path, class: "btn-sm btn-primary" %>
				    </div>
				</div>
			</div>
		</div>

app/views/member/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>注文履歴一覧</h2>

			 <table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
			  <thead>
				<tr>
				  <th colspan="2">注文日</th>
				  <th colspan="4">配送先</th>
				  <th colspan="2">注文商品</th>
			      <th colspan="1">支払金額</th>
			      <th colspan="2">ステータス</th>
			      <th colspan="2">注文詳細</th>
				</tr>
			  </thead>

			 <tbody>
			  <% @orders.each do |order| %>
				<tr>
				  <td colspan="2"><%= order.created_at.strftime('%Y/%m/%d')  %></td>
				  <td colspan="4"><p><%= order.postal_code %></p>
				             	  <p><%= order.address %></p>
				  	              <p><%= order.address_name %></p></td>
				  <td colspan="2">
				  	<% order.order_items.each do |orderitem| %>
				  	<%= orderitem.item.item_name %>
				  	<% end %>
				  </td>
				  <!-- 商品名入れる -->

				  <td colspan="1"><%= order.bill + order.postage %></td>
				  <td colspan="2"><%= order.order_status %></td>
				  <td colspan="2"><%= link_to"表示する",order_path(order.id),class: "btn-sm btn-primary" %></td>
			  <% end %>
				</tr>
			 </tbody>
		    </table>

		</div>
	</div>
</div>

app/views/member/orders/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h3>注文情報入力</h3>
			<%= form_with(model: @order, url: orders_confirm_path, local: true) do |f| %>

			<div class="pay">
				<h4><strong>支払い方法</strong></h4>
				<div>
				<label>
					<%= f.radio_button :payment, "クレジットカード" , {:checked => true} %>クレジットカード
				</label><br />
			    </div>

			    <div>
				<label>
					<%= f.radio_button :payment, "銀行振込" %>銀行振込
				</label>
			    </div>
			</div>

			<div class="address">
				<h4><strong>お届け先</strong></h4>
				<div>
					<label >
						<%= f.radio_button :add, "ご自身の住所" , {:checked => true} %>ご自身の住所
						<p><%= current_member.postal_code %><%= current_member.address %></p>
						<P><%= current_member.surname %><%= current_member.name %></P>
					</label><br />
			    </div>

			    <div>
					<label>
						<%= f.radio_button :add, "登録済み住所からの選択" %>登録済み住所からの選択
					</label><br />
				<%= f.collection_select :address, current_member.addresses, :id, :full_address %>
				</div>

			    <div>
					<label>
						<%= f.radio_button :add, "新しいお届け先" %>新しいお届け先
					</label><br />
					<%= render 'member/orders/newaddress', address: @address %>
			    </div>

			    <div class="row">
					<%= f.submit "確認画面へ進む", class: "btn-sm btn-primary" %>
			    </div>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/member/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>注文履歴詳細</h2>

			<div class="row">
				<div class="col-xs-8">
					<h3>注文情報</h3>
					<table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
						<tbody>
							<tr>
								<th colspan="3">注文日</th>
								<td colspan="9"><%= @order.created_at.strftime('%Y/%m/%d')  %></td>
							</tr>
							<tr>
								<th colspan="3">配送先</th>
								<td colspan="9"><p><%= @order.postal_code %></p>
									<p><%= @order.address %></p>
									<p><%= @order.address_name %></p></td>
								</tr>
								<tr>
									<th colspan="3">支払方法</th>
									<td colspan="9"><%= @order.payment %></td>
								</tr>
								<tr>
									<th colspan="3">ステータス</th>
									<td colspan="9"><%= @order.order_status %></td>
								</tr>
							</tbody>
						</table>
					  </div>

				<div class="col-xs-4">
					<h3>請求情報</h3>
					<table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
						<tbody>
							<tr>
								<th colspan="4">商品合計</th>
								<td colspan="3"><%= @order.bill  %></td>
								<!-- 商品合計出す -->
							</tr>
							<tr>
								<th colspan="4">配送料</th>
								<td colspan="3"><%= @order.postage %></td>
								<!-- 配送料出す -->
							</tr>
							<tr>
								<th colspan="4">ご請求金額</th>
								<td colspan="3"><%= @order.bill + @order.postage  %></td>
								<!-- 請求金額出す -->
							</tr>
						</tbody>
					</table>
				</div>
			</div>

				<div class="row">
					<div class="col-xs-10">
						<table class="table table-hover table-inverse" border="1" style="border-collapse: collapse">
							<thead>
								<tr>
									<th colspan="6">商品</th>
									<th colspan="2">単価（税込）</th>
									<th>個数</th>
									<th>小計</th>
								</tr>
							</thead>
							<tbody>
								<% @order.order_items.each do |orderitem| %>
								<td colspan="6"><%= orderitem.item.item_name %></td>
								<td colspan="2"><%= orderitem.tax_price %></td>
								<td><%= orderitem.number %></td>
								<td><%= orderitem.number * orderitem.tax_price  %></td>
								<% end %>
								<!-- 各項目記載する -->
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/member/orders/thanks.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<p><%= image_tag 'eated.jpg', class: 'hoge' %></p>
			<h1>感謝</h1>
		</div>
	</div>
</div>