config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


scope module: 'member' do
	resources :addresses, only:[:index, :create, :edit, :update, :destroy]


	resources :items, only:[:index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
	resources :cart_items, only:[:create, :update, :index, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/thanks' => 'orders#thanks'
  resources :orders, only:[:new, :index, :show, :create]
	resources :members, only: [:show, :edit, :update]
  root :to => 'members#top'
  get 'confirm' => 'members#confirm'
  delete '/members/:id' => 'members#hide',as: :hide
end


namespace :admin do
	resources :genres,only: [:index,:create,:edit,:update]
	resources :items,only: [:index,:new,:create,:show,:edit,:update]
  resources :admin, only:[:index,:show,:edit,:update]
  resources :orders,only:[:index,:show,:update]
  resources :order_items,only:[:update]  
  get 'top' => 'admin#top'
end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def exist_items?(item)
  	cart_items.exists?(item_id: item.id)
  end


def full_name
    self.surname + self.name
  end

  acts_as_paranoid

validates :surname, presence: true
validates :name, presence: true
validates :kana_surname, presence: true
validates :kana_name, presence: true
validates :postal_code, presence: true, length: { is: 7 }
validates :address, presence: true
validates :phone, presence: true, length: { minimum: 8 }

end

app/controllers/member/addresses_controller.rb
class Member::AddressesController < ApplicationController
	before_action :authenticate_member!

	def index
		@address = Address.new
		@addresses = current_member.addresses
	end

	def create
		@address = Address.new(address_params)
		@address.member_id = current_member.id
		if @address.save
		   redirect_to addresses_path, notice: "successfully created Address!"
	    else
	    	@addresses = Address.all
	    	render :index
	    end
	end

	def edit
		@address = Address.find(params[:id])
	end

	def update
		@address = Address.find(params[:id])
		if @address.update(address_params)
		   redirect_to addresses_path, notice: "successfully update Address!"
		else
			render action: :edit
		end
	end

	def destroy
		@address = Address.find(params[:id])
		@address.destroy
		redirect_to addresses_path
	end

	private

  def address_params
  	params.require(:address).permit(:postal_code, :address, :address_name, :member_id)
  end

end

app/controllers/member/cart_items_controller.rb
class Member::CartItemsController < ApplicationController
	before_action :authenticate_member!

	def create
		@cart_item = CartItem.new(cart_item_params)
		@cart_item.member_id = current_member.id
		@cart_item.save
		redirect_to cart_items_path
	end

	def update
		@cart_item = CartItem.find(params[:id])
		@cart_item.update(cart_item_params)
		redirect_to cart_items_path
	end

	def index
		@cart_item = CartItem.new
		@cart_items = CartItem.where(member_id: current_member)
		@total_price = 0
		@cart_items.each do |cart_item|
			@total_price += cart_item.item.price * cart_item.number
		end
	end

	def destroy
		@cart_item = CartItem.find(params[:id])
		@cart_item.destroy
		redirect_to cart_items_path
	end

	def destroy_all
		@cart_items = CartItem.where(member_id: current_member)
		@cart_items.destroy_all
		redirect_to cart_items_path
	end

	private
	def cart_item_params
		params.require(:cart_item).permit(:item_id, :number, :member_id)
	end

end

# find:id １つのidのみ  where:id以外のカラムを複数　find_by:id以外のカラムも抜けだせる　１つだけもっていける（whereとの違い）

app/controllers/member/items_controller.rb
class Member::ItemsController < ApplicationController

	def index
		@items = Item.all.page(params[:page]).reverse_order
		@genres = Genre.all
	end

	def show
		@genres = Genre.all
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end

	private
	def item_params
		params.require(:item).permit(:genre_id, :item_name, :price, :sale_status, :item_profile, :item_image)
	end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController
	def top
		@items = Item.all
		@jenres = Genre.all
	end

	def show
	end

	def edit
		@member = current_member
	end

	def update
		@member = current_member
		if @member.update(member_params)
			redirect_to member_path(@member)
		else
			render :edit
		end
	end

	def confirm
		@member = current_member
	end

	def hide
		@member = Member.find(params[:id])
		@member.destroy
		redirect_to root_path
	end

	private
	def member_params
		params.require(:member).permit(:surname, :name, :kana_surname, :kana_name, :email, :postal_code, :address, :phone)
	end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
	before_action :authenticate_member!

	def new
		@order = Order.new
		@address = Address.new
	end

	def index
		@orders = current_member.orders
	end

	def show
		@order = Order.find(params[:id])
	end

	def create
		@order = Order.new(session[:order])
		session[:order].clear
		@order.postage = 800
		@order.order_status = 0
		current_member.cart_items.each do |cart_item|
			@order.bill = cart_item.item.price * cart_item.number
		end
		@order.save
		current_member.cart_items.each do |cart_item|
			order_item = OrderItem.new(
				order_id: @order.id,
				number: cart_item.number,
				price: cart_item.item.price,
				production_status: 0,
				item_id: cart_item.item_id
			)
			order_item.save
		end
		current_member.cart_items.destroy_all
		redirect_to orders_thanks_path
	end

	def confirm
		@order = Order.new(order_params)
		@cart_items = CartItem.where(member_id: current_member.id)
		@total_price = 0
		@cart_items.each do |cart_item|
			@total_price += cart_item.item.price * cart_item.number
		end

		add = params[:order][:add]

		if add == "ご自身の住所"
			address = params[:order][:address]
			@address = Address.find_by(id: address)
			@order.address = current_member.address
			@order.address_name = current_member.full_name
			@order.postal_code = current_member.postal_code
		elsif add == "登録済み住所からの選択"
			address = params[:order][:address]
			@address = Address.find_by(id: address)
			@order.address = @address.address
            @order.address_name = @address.address_name
            @order.postal_code = @address.postal_code
		elsif add == "新しいお届け先"
			@address = Address.new(address_params)
			@address.save
			@order.address = @address.address
            @order.address_name = @address.address_name
            @order.postal_code = @address.postal_code
		end

		session[:order] = @order
		session[:order][:bill] = @total_price+800
		session[:order][:member_id] = current_member.id
	end

	def thanks
	end

	private
	def order_params
		params.require(:order).permit(:member_id, :postage, :payment, :order_status, :bill, :postal_code, :address, :address_name)
	end

	def address_params
  		params.require(:address).permit(:postal_code, :address, :address_name, :member_id)
  	end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/member/address_helper.rb
module Member::AddressHelper
end

app/helpers/member/cart_items_helper.rb
module Member::CartItemsHelper
end

app/helpers/member/items_helper.rb
module Member::ItemsHelper
end

app/helpers/member/members_helper.rb
module Member::MembersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/member/members/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h5>本当に退会しますか？</h5>
			<br>
			<p>
				退会すると、会員登録情報や<br>
				これまでの購入履歴が閲覧できなくなります。<br>
				退会する場合は、「退会する」をクリックしてください。
			</p>
			<br>
			<div>
				<%= link_to '退会しない', member_path(current_member.id), calss: "btn btn-info" %>
			</div>
			<div>
				<%= link_to '退会する', hide_path(current_member.id), class: "btn btn-danger", method: :delete %>
			</div>
		</div>
	</div>
</div>

app/views/member/members/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<p>登録情報編集</p>
		</div>
	</div>

	<div class="row">
		<%= form_for (@member) do |f| %>
			<div class="form">
        (<%= f.label :姓 %>)
        <%= f.text_field :surname, autofocus: true, autocomplete: "surname" %>
      </div>

      <div class="form">
        (<%= f.label :名 %>)
        <%= f.text_field :name, autocomplete: "name" %>
      </div>

      <div class="form">
        (<%= f.label :セイ %>)
        <%= f.text_field :kana_surname, autocomplete: "kana_surname" %>
      </div>

      <div class="form">
        (<%= f.label :メイ %>)
        <%= f.text_field :kana_name, autocomplete: "kana_name" %>
      </div>

      <div class="form">
        <%= f.label :メールアドレス %>
        <%= f.email_field :email, autocomplete: "email" %>
      </div>

      <div class="form">
        <%= f.label :郵便番号 %>(ハイフンなし)
        <%= f.text_field :postal_code, autofocus: "postal_code" %>
      </div>

      <div class="form">
        <%= f.label :住所 %>
        <%= f.text_field :address, autofocus: "address" %>
      </div>

      <div class="form">
        <%= f.label :電話番号（ハイフンなし） %>
        <%= f.text_field :phone, autofocus: "phone" %>
      </div>

      <div class="text-center">
        <%= f.submit "編集内容を保存する", class: "btn btn-success" %>  
      </div>
		<% end %>
	  <div><%= link_to '退会する', confirm_path, class: "btn btn-danger" %></div>
	</div>
</div>

app/views/member/members/show.html.erb
<div class="show-container" style="width: 50%; margin: 20px auto;">
	<div class="row">
		<div class="col-12">
			<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">マイページ</h4>
		</div>
		<br>
		<div class="col-12">
			<p style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px; float: left;">登録情報</p>
			<%= link_to '登録情報編集', edit_member_path(current_member), class:"btn btn-info" %>
			<%= link_to 'パスワード変更', edit_member_registration_path(current_member), class:"btn btn-success" %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
		<table class="table table-condensed">
			<tbody>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">氏名</th>
					<td><%= current_member.surname %> <%= current_member.name %></td>
				</tr>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">カナ</th>
					<td><%= current_member.kana_surname %> <%= current_member.kana_name %></td>
				</tr>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">郵便番号</th>
					<td><%= current_member.postal_code %></td>
				</tr>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">住所</th>
					<td><%= current_member.address %></td>
				</tr>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">電話番号</th>
					<td><%= current_member.phone %></td>
				</tr>
				<tr>
					<th style="background-color: #dad7d7; border-bottom: 1px solid #ffff;">メールアドレス</th>
					<td style="border-bottom: 1px solid #dad7d7;"><%= current_member.email %></td>
				</tr>
			</tbody>
		</table>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<p style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px; float: left;">配送先</p>
			<%= link_to '一覧を見る', addresses_path, class:"btn btn-info btn-sm" %>
			<hr>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<p style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px; float: left;">注文履歴</p>
			<%= link_to '一覧を見る', orders_path, class:"btn btn-info btn-sm" %>
			<hr>
		</div>
	</div>
</div>

app/views/member/members/top.html.erb
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-3" style="border: 1px solid #C0C0C0; padding: 10px; margin-top: 40px;">
			<h5 style="text-align: center;">ジャンル検索</h5>
			<hr>
			<ul>
				<% @jenres.each do |jenre| %>
				<li><%= jenre.genre_name %></li>
				<% end %>
			</ul>
		</div>
		<div class="col-6" style="margin-top: 20px;">
			<p style="border: 1px solid #000; padding: 10px; margin: 20px; text-align: center;">ようこそ、NaganoCakeへ！<br>
				このサイトは、ケーキ販売のECサイトになります。<br>
				会員でない方も商品の閲覧はできますが、<br>
				購入には会員登録が必要にあります。
			</p>
		</div>
		<div class="col-3"></div>
	</div>
	<div class="row justify-content-center">
		<div class="col-3"></div>
		<div class="col-9">
			<h5>オススメ商品</h5>
			<div style="display: flex;">
				<% @items.each do |item| %>
				<div style="border: 1px solid #C0C0C0; padding: 5px; margin: 5px;">
					<%= attachment_image_tag item, :item_image, size: "100x100", fallback: "no_image.jpg" %><br>
					<%= link_to item.item_name, item_path(item.id) %><br>
					<%= item.price %>
				</div>
				<% end %>
			</div>
			<br>
				<%= link_to 'もっと見る', items_path %>
		</div>
	</div>
</div>