config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


scope module: 'member' do
	resources :addresses, only:[:index, :create, :edit, :update, :destroy]


	resources :items, only:[:index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
	resources :cart_items, only:[:create, :update, :index, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/thanks' => 'orders#thanks'
  resources :orders, only:[:new, :index, :show, :create]
	resources :members, only: [:show, :edit, :update]
  root :to => 'members#top'
  get 'confirm' => 'members#confirm'
  delete '/members/:id' => 'members#hide',as: :hide
end


namespace :admin do
	resources :genres,only: [:index,:create,:edit,:update]
	resources :items,only: [:index,:new,:create,:show,:edit,:update]
  resources :admin, only:[:index,:show,:edit,:update]
  resources :orders,only:[:index,:show,:update]
  resources :order_items,only:[:update]  
  get 'top' => 'admin#top'
end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :member


	validates :postal_code, presence: true,length: {is: 7 }
	validates :address, presence: true
	validates :address_name, presence: true


	def full_address
		self.postal_code + self.address + self.address_name
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :member

	validates :number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :item_image

	belongs_to :genre
	has_many :cart_items
	has_many :order_items
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def exist_items?(item)
  	cart_items.exists?(item_id: item.id)
  end


def full_name
    self.surname + self.name
  end

  acts_as_paranoid

validates :surname, presence: true
validates :name, presence: true
validates :kana_surname, presence: true
validates :kana_name, presence: true
validates :postal_code, presence: true, length: { is: 7 }
validates :address, presence: true
validates :phone, presence: true, length: { minimum: 8 }

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_items

	enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
	enum payment: {クレジットカード:0, 銀行振込:1}

	validates :payment, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	

	enum production_status: {着手不可:0, 制作待ち:1, 製作中:2, 制作完了:3}

	def tax_price
		tax_price = (price * 1.1).round
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	protected
	def after_sign_in_path_for(resource)
		case resource
		when Member
             root_path
	    when Admin
	    	 admin_top_path
       end
	end



	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:surname, :name, :kana_surname, :kana_name, :email, :postal_code, :address, :phone])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
	end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member/address_helper.rb
module Member::AddressHelper
end

app/helpers/member/items_helper.rb
module Member::ItemsHelper
end

app/helpers/member/members_helper.rb
module Member::MembersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/admin/admin/edit.html.erb
<div class = "container">
  <div class = "row">
   <%= @member.surname %><%= @member.name %>さんの会員情報編集<br>
    
   <table class = 'table'>
    <tr>
      <th>会員ID</th>
      <td><%= @member.id %></td>
    </tr>
    <%= form_with(model:@member, url:admin_admin_path,local:true) do |form| %>	
       <tr>
        <th><%= form.label :氏名 %></th>
	      <td><%= form.text_field :surname %>  <%= form.text_field :name %><br></td>
       </tr>
       <tr>
        <th><%= form.label :フリガナ %></th>
	      <td><%= form.text_field :kana_surname %>  <%= form.text_field :kana_name %></td>
       </tr>
       <tr>
        <th><%= form.label :郵便番号 %></th>
        <td><%= form.text_field :postal_code %></td>
       </tr>
       <tr>
        <th><%= form.label :住所 %></th>
        <td><%= form.text_field :address %></td>
       </tr>
       <tr>
        <th><%= form.label :電話番号 %></th>
        <td><%= form.text_field :phone %></td>
       </tr>
       <tr>
        <th><%= form.label :メールアドレス %></th>
        <td><%= form.text_field :email %></td>
       </tr>
       <tr>
         <th><%= form.label :会員ステータス %></th>
         <td><%= form.radio_button :quit, :true %>
              <%= form.label :quit, "有効", {value: :true, style: "display: inline-block;"} %>
              <%= form.radio_button :quit, :false %>
              <%= form.label :quit, "無効", {value: :false, style: "display: inline-block;"} %>
         </td>
       </tr>
      <th> <%= form.submit :変更を保存する ,class: "btn btn-primary" %></th>       
    <% end %>
  </table>
　</div>
</div>

app/views/admin/admin/index.html.erb
会員一覧ページ<br>
<table class = 'table'>
 <thead>
  <tr>
   <th>会員ID</th>
   <th>氏名</th>
   <th>メールアドレス</th>
   <th>ステータス</th>
  </tr>
 </thead>
 <tbody>
  <% @members.each do  |member| %>
  <tr>
   <td><%= member.id %></td>
   <td><%= link_to member.surname, admin_admin_path(member.id) %><%= link_to member.name, admin_admin_path(member.id)  %></td>
   <td><%= member.email %></td>
   <td><% if member.quit %>
        有効
       <% else %>
        退会済み
       <% end %></td></tr>	
  <% end %>
 </tbody>
</table>

app/views/admin/admin/show.html.erb
<div class = "container">
  <div class = "row">
   会員詳細<br>
   <table class = 'table'>
      <tr>
        <th>顧客ID</th><td><%= @member.id %></td>
      </tr>
      <tr>
        <th>氏名</th><td><%= @member.surname %><%= @member.name %></td>
      </tr>
      <tr>
        <th>フリガナ</th><td><%= @member.kana_surname %><%= @member.kana_name %></td>
      </tr>
      <tr>
        <th>郵便番号</th><td><%= @member.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th><td><%= @member.address %></td>
      </tr>
      <tr>
        <th>電話番号</th><td><%= @member.phone %></td>
      </tr>
      <tr>
        <th>メールアドレス</th><td><%= @member.email %></td>
      </tr>
    </table>
       <%= link_to "編集する", edit_admin_admin_path(@member.id),class: "btn btn-primary"  %>

 </div>
</div>

app/views/admin/admin/top.html.erb
<div class="container">
	<div class="row">
		<div col-xs>
本日の注文件数　<%= @todayorder %>件
		</div>
	</div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>



<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="alert alert-warning" style="color: red;">
	<ul>
		<% model.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="row">
            <a class="navbar-brand" href="/">NaganoCake</a>
            <div class="">
          <nav class="site-nav">
            <ul class="navbar-nav">
            <% if member_signed_in? %>
              <p style="color: #FFF; padding: 0 10px;">ようこそ<%= current_member.surname %> <%= current_member.name %>さん</p>
              <li class="list-items"><%= link_to 'マイページ', member_path(current_member) %></li>
              <li class="list-items"><%= link_to '商品一覧', items_path %></li>
              <li class="list-items"><%= link_to 'カート', cart_items_path %></li>
              <li class="list-items"><%= link_to 'ログアウト',  destroy_member_session_path, method: :delete %></li>
            <% elsif admin_signed_in? %>
              <li class="list-items"><%= link_to '商品一覧', admin_items_path %></li>
              <li class="list-items"><%= link_to '会員一覧', admin_admin_index_path %></li>
              <li class="list-items"><%= link_to '注文履歴一覧', admin_orders_path %></li>
              <li class="list-items"><%= link_to 'ジャンル一覧', admin_genres_path %></li>
              <li class="list-items"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
            <% else %>
              <li class="list-items"><%= link_to '商品一覧', items_path %></li>
              <li class="list-items"><%= link_to '新規登録', new_member_registration_path %></li>
              <li class="list-items"><%= link_to 'ログイン', new_member_session_path %></li>
            <% end %>
            </ul>
          </nav>
      </div>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
  </footer>
  </body>
</html>